# Site settings
title: Sonia Yuxiao Lai
email: yuxiaolai2021@u.northwestern.edu
phone-number: 847-915-0318
url: https://ian-goode.github.io
description: "Welcome to my portfolio page. You can explore my recent works here."
keywords: "Yuxiao Lai"
introduction: "Student in M.S. in Robotics program at Northwestern University looking for job opportunity in robot controls."
meta_author: Yuxiao Lai

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7bb5bd
  primary-rgb: "123, 181, 189" 
  secondary: 7bb5bd
  secondary-dark: 519ea8 

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  mail: Mailing Address
  social: Around the Web
  contacts: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/yuxiao-sonia-lai-b22291195
  - title: github
    url: https://github.com/aonai

# Postal address (add as many lines as necessary)
address:
  - line: Yuxiao Lai, 633 Clark Street
  - line: Evanston, IL 60208

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
